dependencies:
  # this is the link we use to link to the Github.
  # Before @ is address. Here it means https://github.com/smartcontractkit/chainlink-brownie-contracts
  # After the @ is the version of the package
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  # Remember we use solc to compile the contract
  solc:
    # Here we remap all the @chainlink to the link we just store above
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

dotenv: .env
wallets:
  from_key: ${Rinkeby_Key}

# networks store all the information for us to deploy contracts on different blockchain
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: false
  development:
    verify: False
  ganache-local:
    verify: False
